### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by NullVoxPopuli** [dfreeman/fccts-in-v2#1]
Folks are somehow still finding this repo. :upside_down_face: 

The way we support gjs in v2 addons is in the blueprint now -- folks can see how it's set up via:

```
npx ember-cli addon my-addon -b @embroider/addon-blueprint
```

**Comment by dfreeman** [comment]
Can you PR a change to README pointing folks in the right direction?

**Comment by NullVoxPopuli** [comment]
Sure thing: https://github.com/dfreeman/fccts-in-v2/pull/2
